services:
  app:
    build: .
    image: bosemene/final2024:latest
    container_name: app2-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://finalsprintdb.cr8aqaqos0eg.us-east-1.rds.amazonaws.com/travel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: idumubo123
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
















